package proyecto_final.tienda.model;

import java.util.Date;

/**
 * Descuentos generated by hbm2java
 */
public class Descuentos implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private Integer id;
	private String codigo;
	private Float descuento;
	private Date fechaInicio;
	private Date fechaFin;

	public Descuentos() {
	}

	public Descuentos(Date fechaInicio, Date fechaFin) {
		this.fechaInicio = fechaInicio;
		this.fechaFin = fechaFin;
	}

	public Descuentos(String codigo, Float descuento, Date fechaInicio, Date fechaFin) {
		this.codigo = codigo;
		this.descuento = descuento;
		this.fechaInicio = fechaInicio;
		this.fechaFin = fechaFin;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	public Float getDescuento() {
		return this.descuento;
	}

	public void setDescuento(Float descuento) {
		this.descuento = descuento;
	}

	public Date getFechaInicio() {
		return this.fechaInicio;
	}

	public void setFechaInicio(Date fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	public Date getFechaFin() {
		return this.fechaFin;
	}

	public void setFechaFin(Date fechaFin) {
		this.fechaFin = fechaFin;
	}

	@Override
	public String toString() {
		return "Descuentos [id=" + id + ", codigo=" + codigo + ", descuento=" + descuento + ", fechaInicio="
				+ fechaInicio + ", fechaFin=" + fechaFin + "]";
	}
	
	

}
