package proyecto_final.tienda.model;

/**
 * OpcionesMenu generated by hbm2java
 */
public class OpcionesMenu implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private Integer id;
	private Integer idRol;
	private String nombreOpcion;
	private String urlOpcion;

	public OpcionesMenu() {
	}

	public OpcionesMenu(Integer idRol, String nombreOpcion, String urlOpcion) {
		this.idRol = idRol;
		this.nombreOpcion = nombreOpcion;
		this.urlOpcion = urlOpcion;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getIdRol() {
		return this.idRol;
	}

	public void setIdRol(Integer idRol) {
		this.idRol = idRol;
	}

	public String getNombreOpcion() {
		return this.nombreOpcion;
	}

	public void setNombreOpcion(String nombreOpcion) {
		this.nombreOpcion = nombreOpcion;
	}

	public String getUrlOpcion() {
		return this.urlOpcion;
	}

	public void setUrlOpcion(String urlOpcion) {
		this.urlOpcion = urlOpcion;
	}

	@Override
	public String toString() {
		return "OpcionesMenu [id=" + id + ", idRol=" + idRol + ", nombreOpcion=" + nombreOpcion + ", urlOpcion="
				+ urlOpcion + "]";
	}
	
	

}
