package tienda.proyecto_final.model;

/**
 * MetodosPago generated by hbm2java
 */
public class MetodosPago {
	
	public static String TARJETA = "Tarjeta";
	public static String PAYPAL = "Paypal";
	
	private Integer id;
	private String metodoPago;

	public MetodosPago() {
	}

	public MetodosPago(String metodoPago) {
		this.metodoPago = metodoPago;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getMetodoPago() {
		return this.metodoPago;
	}

	public void setMetodoPago(String metodoPago) {
		this.metodoPago = metodoPago;
	}

	@Override
	public String toString() {
		return "MetodosPago [id=" + id + ", metodoPago=" + metodoPago + "]";
	}

	
	
}
