package tienda.proyecto_final.model;

import java.sql.Date;
import java.time.LocalDate;
import java.util.ArrayList;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

/**
 * Pedidos generated by hbm2java
 */
@Entity
public class Pedidos {
	
	public static String SIN_REALIZAR = "Sin realizar";
	
	public static String ENVIADO = "Enviado";
	public static String PENDIENTE = "Pendiente";
	public static String PENDIENTE_CANCELAR = "Pendiente de cancelar";
	public static String CANCELADO = "Cancelado";
	
	
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private Long id;
	private Long idUsuario;
	private Date fecha;
	private String metodoPago;
	private String estado;
	private String numFactura;
	private Double total;

	public Pedidos() {
	}

	public Pedidos(Date fecha) {
		this.fecha = Date.valueOf(LocalDate.now());
	}
	public Pedidos(Long id, Long idUsuario, Date fecha, String metodoPago, String estado, String numFactura, Double total) {
		this.id = id;
		this.idUsuario = idUsuario;
		this.fecha = fecha;
		this.metodoPago = metodoPago;
		this.estado = estado;
		this.numFactura = numFactura;
		this.total = total;
	}
	public Pedidos(Long idUsuario, Date fecha, String metodoPago, String estado, String numFactura, Double total) {
		this.idUsuario = idUsuario;
		this.fecha = fecha;
		this.metodoPago = metodoPago;
		this.estado = estado;
		this.numFactura = numFactura;
		this.total = total;
	}
	public Pedidos(Long idUsuario, String metodoPago, String estado, String numFactura, Double total) {
		this.idUsuario = idUsuario;
		this.fecha = Date.valueOf(LocalDate.of(2021, 5, 14));
		this.metodoPago = metodoPago;
		this.estado = estado;
		this.numFactura = numFactura;
		this.total = total;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Long getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(Long idUsuario) {
		this.idUsuario = idUsuario;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}
	public void setFechaActual() {
		this.fecha = Date.valueOf(LocalDate.now());
	}

	public String getMetodoPago() {
		return this.metodoPago;
	}

	public void setMetodoPago(String metodoPago) {
		this.metodoPago = metodoPago;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public String getNumFactura() {
		return this.numFactura;
	}

	public void setNumFactura(String numFactura) {
		this.numFactura = numFactura;
	}

	public Double getTotal() {
		return this.total;
	}

	public void setTotal(Double total) {
		this.total = total;
	}

	@Override
	public String toString() {
		return "Pedidos [id=" + id + ", idUsuario=" + idUsuario + ", fecha=" + fecha + ", metodoPago=" + metodoPago
				+ ", estado=" + estado + ", numFactura=" + numFactura + ", total=" + total + "]";
	}

	public void calcularTotal(ArrayList<DetallesPedido> detalles) {
		total = 0d;
		
		for(DetallesPedido d: detalles)
			total += d.getTotal();
	}
	
}
