package tienda.proyecto_final.model;

/**
 * Roles generated by hbm2java
 */
public class Roles implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private Integer id;
	private String rol;

	public Roles() {
	}

	public Roles(String rol) {
		this.rol = rol;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getRol() {
		return this.rol;
	}

	public void setRol(String rol) {
		this.rol = rol;
	}

	@Override
	public String toString() {
		return "Roles [id=" + id + ", rol=" + rol + "]";
	}

	
	
}
