package curso.java.tienda.model;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

/**
 * OpcionesMenu generated by hbm2java
 */
@Entity
public class OpcionesMenu {
	
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private Long id;
	private Long idRol;
	private String nombreOpcion;
	private String urlOpcion;

	public OpcionesMenu() {
	}
	public OpcionesMenu(Long id, Long idRol, String nombreOpcion, String urlOpcion) {
		this.id = id;
		this.idRol = idRol;
		this.nombreOpcion = nombreOpcion;
		this.urlOpcion = urlOpcion;
	}
	public OpcionesMenu(Long idRol, String nombreOpcion, String urlOpcion) {
		this.idRol = idRol;
		this.nombreOpcion = nombreOpcion;
		this.urlOpcion = urlOpcion;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Long getIdRol() {
		return this.idRol;
	}

	public void setIdRol(Long idRol) {
		this.idRol = idRol;
	}

	public String getNombreOpcion() {
		return this.nombreOpcion;
	}

	public void setNombreOpcion(String nombreOpcion) {
		this.nombreOpcion = nombreOpcion;
	}

	public String getUrlOpcion() {
		return this.urlOpcion;
	}

	public void setUrlOpcion(String urlOpcion) {
		this.urlOpcion = urlOpcion;
	}

	@Override
	public String toString() {
		return "OpcionesMenu [id=" + id + ", idRol=" + idRol + ", nombreOpcion=" + nombreOpcion + ", urlOpcion="
				+ urlOpcion + "]";
	}
	
	

}
