package curso.java.tienda.model;

/**
 * Roles generated by hbm2java
 */
public class Roles implements java.io.Serializable {
	
	public static Long ADMIN = 1l;
	public static Long EMPLEADO = 2l;
	public static Long CLIENTE = 3l;
	public static Long ANONIMO = 4l;

	private static final long serialVersionUID = 1L;
	
	private Integer id;
	private String rol;

	public Roles() {
	}

	public Roles(String rol) {
		this.rol = rol;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getRol() {
		return this.rol;
	}

	public void setRol(String rol) {
		this.rol = rol;
	}

	@Override
	public String toString() {
		return "Roles [id=" + id + ", rol=" + rol + "]";
	}

	
	
}
