package curso.java.tienda.model;

/**
 * Valoraciones generated by hbm2java
 */
public class Valoraciones implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private Long id;
	private Long idProducto;
	private Long idUsuario;
	private Integer valoracion;
	private String comentario;

	public Valoraciones() {
	}

	public Valoraciones(Long idProducto, Long idUsuario, Integer valoracion, String comentario) {
		this.idProducto = idProducto;
		this.idUsuario = idUsuario;
		this.valoracion = valoracion;
		this.comentario = comentario;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Long getIdProducto() {
		return this.idProducto;
	}

	public void setIdProducto(Long idProducto) {
		this.idProducto = idProducto;
	}

	public Long getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(Long idUsuario) {
		this.idUsuario = idUsuario;
	}

	public Integer getValoracion() {
		return this.valoracion;
	}

	public void setValoracion(Integer valoracion) {
		this.valoracion = valoracion;
	}

	public String getComentario() {
		return this.comentario;
	}

	public void setComentario(String comentario) {
		this.comentario = comentario;
	}

	@Override
	public String toString() {
		return "Valoraciones [id=" + id + ", idProducto=" + idProducto + ", idUsuario=" + idUsuario + ", valoracion="
				+ valoracion + ", comentario=" + comentario + "]";
	}
	
	

}
